### ISSUE TITLE
Swiping lacks "snap" (sometimes)

### ISSUE THREAD

**Issue by elondaits** [IMAGINARY/snapshot-slider#28]
This was noticed on a small screen (might not be easily noticeable on a large one):

Sometimes when swiping slowly and trying to move the next snapshot to the center of the screen it lacked "snap" (the snapshot auto-adjusting to the center position).

**Comment by porst17** [comment]
I noticed this as well. This seems to be a bug or at least weird behavior of the [Swiper](http://idangero.us/swiper/) library. It needs to be investigated further and reduced to a minimal working example that we could send in as a bug report.

**Comment by porst17** [comment]
Swiper v3.1.5 (we are on v4.3.x) already introduced `freeModeMinimumVelocity`, which is set to a quite low value by default. I increased it by a factor of 5. Now slides will only keep moving if you swipe fast enough (and eventually stop on some slide). Otherwise they should snap to the closest slide. At least I could not reproduce the slow automatic movement.
